In [1]:
import pandas
import selenium
from selenium import webdriver
import time
import requests
import pandas as pd

In [2]:
url1="https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=400001"

In [3]:
driver1=webdriver.Chrome("chromedriver1.exe")
driver1.get(url1)

In [4]:
City=[400001,110001,122001,411001,560001,500001,600001,700001,380001,390001,462001,134101,121001,201001,450001,302001,682001,
     226001,141001,250001,563102,440001,422001,132101,800001,360001,124001,131001,394101,140604]

In [5]:
Url=[]
for i in City:
    Url.append(f'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId={i}')
Url

['https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=400001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=110001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=122001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=411001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=560001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=500001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=600001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=700001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=380001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=390001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=462001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=134101',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=121001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=201001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=450001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=302001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=682001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=226001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=141001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=250001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=563102',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=440001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=422001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=132101',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=800001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=360001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=124001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=131001',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=394101',
 'https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=140604']

In [6]:
KM=[]
Owner=[]
Fuel=[]
Description=[]
Price=[]
Transmission=[]
Variant=[]
Description1=[]
City=[]


for i in Url:
    driver1.get(i)
    driver1.execute_script("window.scrollTo(0, 12000000);")
    time.sleep(25)
    
    
    city=driver1.find_elements_by_xpath("//p[@class='_1OR7d']")        
    km=driver1.find_elements_by_xpath("//ul[@class='bVR0c']//li[1]")
    for i in km:
        for j in city:
            KM.append(i.text)
            City.append(j.text)
        
    owner=driver1.find_elements_by_xpath("//ul[@class='bVR0c']//li[2]")
    for i in owner:
        Owner.append(i.text)
        
    fuel=driver1.find_elements_by_xpath("//ul[@class='bVR0c']//li[3]")
    for i in fuel:
        Fuel.append(i.text)
        
    desc=driver1.find_elements_by_xpath("//h2[@class='_3FpCg']")
    for i in desc:
        Description.append(i.text)
        
    price=driver1.find_elements_by_xpath("//div[@class='_7udZZ']")
    for i in price:
        Price.append(i.text)
    
    trans=driver1.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in trans:
        Transmission.append(i.text)
        
    variant=driver1.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in variant:
        Variant.append(i.text)
        
    desc1=driver1.find_elements_by_xpath("//ul[@class='bVR0c']")
    for i in desc1:
        Description1.append(i.text)
        
Year=[i.split(' ',2)[0] for i in Description]
Brand_Name=[i.split(' ',2)[1] for i in Description]
Model=[i.split(' ',2)[2] for i in Description]       
        

        
print('Length of Km',len(KM))
print('Length of Owner',len(Owner))
print('Length Of Fuel',len(Fuel))
print('Length Of Description',len(Description))
print('Length Of Price',len(Price))
print('Length Of Transmission',len(Transmission))
print('Length Of Variant',len(Variant))
print('Length Of Year',len(Year))
print('Length Of Brand_Name',len(Brand_Name))
print('Length Of Model',len(Model))
print('Length Of Description1',len(Description1))

Length of Km 4059
Length of Owner 4059
Length Of Fuel 4059
Length Of Description 4059
Length Of Price 4059
Length Of Transmission 4059
Length Of Variant 4059
Length Of Year 4059
Length Of Brand_Name 4059
Length Of Model 4059
Length Of Description1 4059

In [ ]:
KM1=[i.split(' ',2)[0] for i in Description1]
KM1

In [9]:
Car=pd.DataFrame()

Car['year']=Year
Car['company name']=Brand_Name
Car['car model']=Model
Car['km driven']=KM1
Car['ownership']=Owner
Car['Fuel']=Fuel
Car['Price']=Price
Car['Transmission']=Transmission
Car['Variant']=Variant
Car['City']=City
Car

,year,company name,car model,km driven,ownership,Fuel,Price,Transmission,Variant,City
0,2009,Toyota,Camry,"99,864",1st Owner,Petrol,"₹3,07,299",Automatic,W4 AT Automatic,Mumbai
1,2016,Maruti,Baleno,"50,022",1st Owner,Petrol,"₹5,32,199",Manual,ZETA 1.2 K12 Manual,Mumbai
2,2020,Skoda,Rapid,"6,981",1st Owner,Petrol,"₹9,01,299",Manual,1.0 AMBITION TSI MT Manual,Mumbai
3,2018,Hyundai,Creta,"48,945",3rd Owner,Diesel,"₹9,09,099",Manual,1.4 E PLUS CRDI Manual,Mumbai
4,2020,Hyundai,VENUE,547,1st Owner,Petrol,"₹8,26,399",Manual,S MT 1.2 KAPPA Manual,Mumbai
...,...,...,...,...,...,...,...,...,...,...
4054,2015,Maruti,Swift Dzire,"65,774",2nd Owner,Petrol,"₹4,56,599",Manual,VXI 1.2 BS IV Manual,Zirakpur
4055,2016,Maruti,Celerio,"55,107",1st Owner,Petrol,"₹3,96,299",Manual,VXI Manual,Zirakpur
4056,2016,Maruti,Vitara Brezza,"90,783",2nd Owner,Diesel,"₹6,69,099",Manual,ZDI Manual,Zirakpur
4057,2016,Hyundai,Elite i20,"25,697",1st Owner,Petrol,"₹5,48,199",Manual,SPORTZ 1.2 Manual,Zirakpur
4058,2013,Maruti,Swift,"1,04,175",1st Owner,Diesel,"₹3,84,299",Manual,VDI Manual,Zirakpur

In [11]:
Car.to_csv('Car_Prise2.csv')